# Generated by Django 5.0.7 on 2024-07-27 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('original_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarybullets.text')),
            ],
        ),
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('original_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarybullets.text')),
            ],
        ),
    ]
