# Generated by Django 5.0.7 on 2024-07-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarybullets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='original_text',
        ),
        migrations.RemoveField(
            model_name='bulletpoint',
            name='original_text',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
