# Generated by Django 5.0.7 on 2024-07-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarybullets', '0002_remove_summary_original_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletpoint',
            name='bullet_points',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='bulletpoint',
            name='original_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='original_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='summary',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
