# Generated by Django 5.0.7 on 2024-07-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarybullets', '0003_bulletpoint_bullet_points_bulletpoint_original_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
