# Generated by Django 5.0.7 on 2024-07-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarybullets', '0004_alter_summary_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletpoint',
            name='bullet_points',
            field=models.TextField(null=True),
        ),
    ]
