# Generated by Django 5.0.7 on 2024-07-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarybullets', '0005_alter_bulletpoint_bullet_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletpoint',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
